export const CREDIT_COST_CREATE_PROJECT = 15;
export const CREDIT_COST_CREATE_TASK = 5;
export const CREDIT_COST_RUN_TASK = 5;
export const CREDIT_COST_SECURITY_CHECK = 2;
export const CREDIT_COST_SERVER_SCAN = 30;
export const CREDIT_COST_SERVER_TELEMETRY = 1;
