ALTER TABLE `organizations`
  ADD COLUMN `credits` INT NOT NULL DEFAULT 0,
  ADD COLUMN `lastCreditedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `lastDebitAt` DATETIME(3) NULL,
  ADD COLUMN `scanSuspendedAt` DATETIME(3) NULL;
