ALTER TABLE `organizations`
  ADD COLUMN IF NOT EXISTS `credits` INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `lastCreditedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS `lastDebitAt` DATETIME(3) NULL,
  ADD COLUMN IF NOT EXISTS `scanSuspendedAt` DATETIME(3) NULL;
